<?php
/**
 *author:yyx
 *create_time:2018/1/18 11:13
 *description:
 */
namespace console\controllers;
use shmilyzxt\queue\Worker;
class WorkerController extends \yii\console\Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionListen($queueName='default',$attempt=10,$memeory=128,$sleep=3 ,$delay=0){
        Worker::listen(\Yii::$app->queue,$queueName,$attempt,$memeory,$sleep,$delay);
    }
}

